# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParkSpace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  inhibit_all_warnings!
  
  use_frameworks!
  
  # Pods for ParkSpace
  pod 'M13Checkbox', :inhibit_warnings => true
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SideMenu'
  pod 'TextFieldEffects'
  
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database’
  pod 'Firebase/Auth’

  target 'ParkSpaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkSpaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
